### ISSUE TITLE
Doesn’t work with ARSCNView

### ISSUE THREAD

**Issue by okaris** [laanlabs/SCNTechniqueGlow#1]
The code works fine with SceneKit but it doesnt generate the glow in ARKit. 

With my limited understanding of Metal I tried debugging. The mask pass works as it should but the blur passes doesn’t generate anything.

**Comment by cclaan** [comment]
Hmm, we're using it with ARSCNView. Would you mind sharing your code? 
Are you testing on device or simulator?

**Comment by okaris** [comment]
Adding the SCNTechnique

`if let path = Bundle.main.path(forResource: "NodeTechnique", ofType: "plist") {
        if let dict = NSDictionary(contentsOfFile: path) as? [String : AnyObject] {
          let technique = SCNTechnique(dictionary:dict)
          sceneView.technique = technique
        } else {
          print("cast error")
        }
      } else {
        print("plist error")
      }`

Activating bitMask

`objectNode.categoryBitMask = 2
objectNode.childNodes.forEach { $0.categoryBitMask = 2}`

**Comment by okaris** [comment]
Found the culprit, but still trying to figure out the underlying reason. Removing the following line fixed the issue:
`      sceneView.antialiasingMode = .multisampling4X
`
But this is not a viable solution for me. Do you have any idea about why antialiasing causes outline to fail?

**Comment by cclaan** [comment]
That is odd, I'm seeing the same thing. I probably won't look into this but let us know if you figure anything out. Can you tell if the SCNTechnique is being used at all or just disabled with antialiasing on?

**Comment by okaris** [comment]
If I debug the GPU frame I see that passes are added and mask pass works. Blur passes don't receive the texture from mask pass.

**Comment by wave-electron** [comment]
I just tested this in iOS 11.4 and it does generate the glow in a ARSCNView 

![img_3jun2018at110714am](https://user-images.githubusercontent.com/16273780/40882221-6e7f1218-671e-11e8-8d0f-3b58448a9cd2.jpg)

**Comment by willperkins** [comment]
I've added a working example with ARKit at 29bcd3c . If you're still having problems, re-open this issue.
