### ISSUE TITLE
Artifact in the material border

### ISSUE THREAD

**Issue by abbana** [laanlabs/SCNTechniqueGlow#14]
Hi,

hope you are good.

I am applying the technique to a SCNPlane and I have an ugly artifact in the border as per screenshot attached.

Can this artifact be removed someway or at least mitigated?
![technique](https://user-images.githubusercontent.com/32463975/79509343-3f2fb500-8033-11ea-8a41-abab14180b62.jpg)

**Comment by cclaan** [comment]
Any chance you can upload a sample project showing this artifact?

**Comment by abbana** [comment]
> Any chance you can upload a sample project showing this artifact?

@cclaan Sure, any SCNPlane or SCNtext nodes shown that behaviour. I have not tested other shapes. It seems to me is function of the NODE in regards to the camera. The above is a SCNPlane and the line is visible on the upper part of the node only, but still not usable.

Regarding the implementation I just 

- Copied the technique
- Added the node into bitmask 2 
- Activate the technique in sceneview

**Comment by abbana** [comment]
Hi,

issue is on the below line:

if ( maskColor.g > 0.5 ) {
return half4(FragmentColor);
}

All the rest works as supposed.

Thanks for the good job.

**Comment by cclaan** [comment]
Were you able to fix it? sorry i haven't had a chance to look into this.

**Comment by abbana** [comment]
Correct, closing the issue now.
