### ISSUE TITLE
categoryBitMask does not work on nodes with children

### ISSUE THREAD

**Issue by wave-electron** [laanlabs/SCNTechniqueGlow#7]
I have only been able to get the categoryBitMask to work on Nodes that either don't have any children or you have to flatten first to make work. 

I'm using the following test code to set them all to say categoryBitMask = 2

    let count = self.parentNode.childrenNodes.count
    for i in 0...count-1 {
    self.parentNode.childNodes[i].categoryBitMask = 2
    }

If the  childNodes to the parentNode don't have children it will switch off the glow. Otherwise I'm getting the glow around the whole model. 

I also tried setting self.parentNode.categoryBitMask = 2

it also won't work if that parentNode has children.

What I'm trying to achieve is the whole model starts off with no glow. You then can tap a node and the glow will appear for that node.

**Comment by cclaan** [comment]
You need to set the categoryBitMask on all children of the root node recursively. I've pushed an extension that does this so you can just call node.setHighlighted( true | false )

**Comment by wave-electron** [comment]
I realised today after playing  around with it a bit longer that it was something I was doing wrong ... but thanks anyway for the scnnode extension... its a nice coding example.
